"""Initial migration

Revision ID: 325568317df4
Revises: 
Create Date: 2025-01-03 16:49:23.898438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '325568317df4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('downloads',
    sa.Column('uid', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('path', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('downloaded_at', sa.DateTime(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('articles',
    sa.Column('uid', sa.String(), nullable=True),
    sa.Column('path', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('download_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['download_id'], ['downloads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ai_articles',
    sa.Column('uid', sa.String(), nullable=True),
    sa.Column('path', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('article_id', sa.Integer(), nullable=True),
    sa.Column('query', sa.String(), nullable=True),
    sa.Column('response', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ai_articles')
    op.drop_table('articles')
    op.drop_table('downloads')
    # ### end Alembic commands ###
